version: '3.9'

services:
  iphistory:
    image: ghcr.io/skidoodle/iphistory:main
    container_name: iphistory
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - data:/app

volumes:
  data:
    driver: local
